### ISSUE TITLE
[issue] Can't change program in Burp

### ISSUE THREAD

**Issue by pdelteil** [honoki/bbrf-burp-plugin#1] opened 2021-04-18 05:04 UTC
I'm starting to use the plugin, I wanted to change the program selected on it, for some reason it started a random program, but I couldn't change it. The program loads on the GUI on the BBRF tab, but even doing 'Verify', 'Save' and 'Copy' didn't change the program. So, this is what happens:

- Running the Burp scanner, the plugin does try to add domains and urls to the correct program (the one set on the BBRF tab) 
- While doing Right click + add domain/url it tries to add them to the other program I can't get rid of. 

I'm using Burp Professional v2021.3.3.

**Comment by honoki** [comment] 2021-11-07 16:54
I located a small bug where the plugin would try to add domains and urls to the current active program (as specified in `config.json`) rather than the chosen program in the settings tab. This should be fixed in the next commit.

I think that should solve the issue you described above.

**Closed as completed** 2021-11-07 17:00 UTC

**Comment by honoki** [comment] 2021-11-07 17:19
Can you verify if the issue is fixed in the latest release, @pdelteil ?
